In [1]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [0]:
v= torch.tensor([1,2,3,4])

In [4]:
print(v)

tensor([1, 2, 3, 4])


In [5]:
print(v.dtype)

torch.int64


In [6]:
print(v[2:3])

tensor([3])


In [0]:
f = torch.FloatTensor([1,2,3,4,5,6])

In [8]:
print(f.dtype)

torch.float32


In [9]:
print(f.size())

torch.Size([6])


In [12]:
# Reshaping tensor

v.view((2,2))

tensor([[1, 2],
        [3, 4]])

In [17]:
v.view((2,-1)) # Automatically adjusts the tensors

tensor([[1, 2],
        [3, 4]])

In [21]:
# Switching between numpy array and tensors

a=np.array([1,2,3,4,5])

tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [22]:
# converting back to numpy from tensor

numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
