In [0]:
import torch

In [5]:
one_d= torch.arange(0, 9)
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [6]:
two_d= one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
two_d[0,0]

tensor(0)

In [8]:
two_d.dim()

2

In [9]:
x=torch.arange(18).view(2,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [10]:
x.dim()

3